### ISSUE TITLE
preprocess.py doesn't work on yoochoose-clicks.dat

### ISSUE THREAD

**Issue by ritchie46** [CRIPAC-DIG/SR-GNN#34] opened 2020-01-15 10:03 UTC
Running `python preprocess.py --dataset=yoochoose` assumes a CSV header, which is not available in the standard `yoochoose-clicks.dat` downloaded from the source in the README. The assumed formatting of the timestamp data is also not correct.

**Comment by SXKDZ** [comment] 2020-01-15 11:52
Duplicate of #18

**Closed as completed by SXKDZ** 2020-01-15 11:52 UTC
